# Generated by Django 4.1.1 on 2022-10-15 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'verbose_name_plural': 'Artículos'},
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterModelOptions(
            name='seccion',
            options={'verbose_name_plural': 'Secciones'},
        ),
    ]
