# Generated by Django 4.1.1 on 2022-10-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_articulo_options_alter_autor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='fecha',
        ),
    ]
