# Generated by Django 4.1.1 on 2022-10-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_articulo_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
